### ISSUE TITLE
Auth_*::logged_in() should always call parent::logged_in()

### ISSUE THREAD

**Issue by samwilson** [kohana/auth#19]
Should Auth drivers, when implementing `logged_in($role = NULL)`, return a value that takes into account the value returned by the parent class (`Auth`), so that an application-level `Auth` class can also provide login status?

For example (where `$this->has_role($role)` does what it sounds like it would):

```
public function logged_in($role = NULL)
{
    $logged_in = parent::logged_in($role);
    return ($logged_in OR $this->has_role($role));
}
```

I am coming up against a situation where the LDAP auth driver is providing one set of roles, but we also need the application to be able to add to these.

Does this make sense?

**Comment by acoulton** [comment]
@samwilson I don't think that's a good idea. The default driver returns TRUE if a user is logged in without checking the role at all, so with your proposal any driver with a has_role that returned FALSE would still return TRUE if a user is logged in.

I think you could solve your usecase instead by implementing a new driver that extends the LDAP one and adds whatever custom role logic before/after the call to `parent::logged_in` as required. Although Kohana's transparent extension is useful sometimes, it's generally much better IMHO to customise by extension and subclassing where you can rather than injecting logic further up the class tree.
